inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

Metrics:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/trace_location/cli.rb'
