name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.ruby }}
    strategy:
      matrix:
        experimental: [false]
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        include:
          - { ruby: head, experimental: true }
    env:
      RUBYOPT: "-W:deprecated"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        timeout-minutes: 5
        run: bundle exec rake
