name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.6"
          - "2.7"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        timeout-minutes: 5
        run: bundle exec rake
